name: Run Unit Tests and Lint Files
on: push

jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18.19
      - working-directory: ./applications/sckanner/frontend
        name: Install, Build and Test
        run: |
          yarn
          yarn run build
          yarn run test
  unit_test-django:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - working-directory: ./applications/sckanner/backend
        name: Install, Build and Test
        run: |
          pip install -r requirements.txt
          python manage.py test
