name: Run Unit Tests and Lint Files
on: push

jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18.19
      - working-directory: ./applications/sckanner/frontend
        name: Frontend linter
        run: |
          yarn
          yarn run build
          yarn run lint
  unit_test-django:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.16
      - name: Install dependencies
        working-directory: ./applications/sckanner/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Clone cloud harness
        working-directory: ./applications/sckanner/backend
        run: |
          git clone -b 'v2.4.3' https://github.com/metacell/cloud-harness
          cd cloud-harness && bash install.sh
      - name: Install cloud harness common
        working-directory: ./applications/sckanner/backend/cloud-harness/libraries/cloudharness-common
        run: |
          pip install -e .
      - name: Install cloud harness django
        working-directory: ./applications/sckanner/backend/cloud-harness/infrastructure/common-images/cloudharness-django/libraries/cloudharness-django
        run: |
          pip install -e .
      - name: Harness Deployment command
        working-directory: ./applications/sckanner/backend
        run: |
          cd ../../..
          harness-deployment cloud-harness . -i sckanner -e dev-test -d sckanner.local -n sckanner -u -dtls --no-cd -l
      - working-directory: ./applications/sckanner/backend
        name: Run tests
        run: |
          python manage.py test
