name: Run Unit Tests and Lint Files
on: push

jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18.19
      - working-directory: ./applications/sckanner/frontend
        name: Frontend linter
        run: |
          yarn
          yarn run build
          yarn run lint
  unit_test-django:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.16
      - working-directory: ./applications/sckanner/backend
        name: Backend testing
        run: |
          pip install -r requirements.txt
          git clone -b 'v2.4.3' https://github.com/metacell/cloud-harness && cd cloud-harness/libraries/cloudharness-common && pip install -e . && cd -
          cd cloud-harness/infrastructure/common-images/cloudharness-django/libraries/cloudharness-django && pip install -e . && cd -
          python manage.py test
